# Generated by Django 3.2.7 on 2023-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'Done')], default=1),
        ),
    ]
