# Generated by Django 3.2.7 on 2023-11-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231109_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='qiwi_pass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='phones',
        ),
        migrations.AddField(
            model_name='task',
            name='phones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='qiwi_wallet',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='QIWWallet',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
