# Generated by Django 3.2.7 on 2023-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231113_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'Done'), (0, 'Stopped'), (4, 'Start')], default=1),
        ),
    ]
