# Generated by Django 3.2.7 on 2023-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
