# Generated by Django 3.2.7 on 2023-11-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(default='loading...', max_length=50),
        ),
    ]
